# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('StartTime', models.DateField(auto_now_add=True)),
                ('EndTime', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(max_length=100)),
            ],
        ),
    ]
