# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskgroup', '0002_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='EndTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='StartTime',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
